#.travis.yml

language: node_js
node_js:
  - "9.3"

script:
  - npm run build

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true